HACK: x86/bugs: Don't use sched_smt_active() yet
This reverts commit 1572793b498d, partially reverts commits f67fafb88c46 and
f55e301ec4d5. I assume this function isn't ready because the similar change
doesn't get applied to kernel/cpu.c yet. Fixes the following errors reported
by BFD linker:

  /opt/kud/x86_64-linux-gnu/bin/x86_64-linux-gnu-ld.bfd: arch/x86/kernel/cpu/bugs.o:(__jump_table+0x88): undefined reference to `sched_smt_present'
  /opt/kud/x86_64-linux-gnu/bin/x86_64-linux-gnu-ld.bfd: arch/x86/kernel/cpu/bugs.o:(__jump_table+0xa0): undefined reference to `sched_smt_present'
  /opt/kud/x86_64-linux-gnu/bin/x86_64-linux-gnu-ld.bfd: arch/x86/kernel/cpu/bugs.o:(__jump_table+0x118): undefined reference to `sched_smt_present'
  /opt/kud/x86_64-linux-gnu/bin/x86_64-linux-gnu-ld.bfd: arch/x86/kernel/cpu/bugs.o:(__jump_table+0x130): undefined reference to `sched_smt_present'
  make: *** [Makefile:1024: vmlinux] Error 1

Signed-off-by: Albert I <krascgq@outlook.co.id>