HACK: kvm-intel: Revert sched_smt_active() change from commit f29a8be0e5d2
...back to cpu_smt_control in order to fix linking with Gold.

ERROR: "sched_smt_present" [arch/x86/kvm/kvm-intel.ko] undefined!

Signed-off-by: Albert I <krascgq@outlook.co.id>