fs/bcachefs: Workaround LLVM integrated-as errors
If we really want to optimize the asm part of the code...

  fs/bcachefs/bset.c:1193:6: error: unknown token in expression
          asm(".intel_syntax noprefix;"
              ^
  <inline asm>:1:37: note: instantiated into assembly here
          .intel_syntax noprefix;prefetcht0 [%rbx - 127 + 64 * 0];prefetcht0 [%rbx - 127 + 64 * 1];prefetcht0 [%rbx - 127 + 64 * 2];prefetcht0 [%rbx - 127 + 64 * 3];.att_syntax prefix;
                                             ^

  (rest are trimmed for clarity, since they're similar errors)

I'm not sure if this is correct but I don't care if it doesn't anyway.

Signed-off-by: Albert I <kras@raphielgang.org>